"""Growable feature cache for CONCURRENT DAgger -- paper Fig. 3.

Fig. 3 runs two sampling processes at the same time and one training process:

    Simulation #1 (uniform, offline)  --,
                                        +--> Database {a, a*} --> Training
    Simulation #2 (DAgger, uses          |         ^
        the CURRENT policy's action)  ---'         |
                    Synchronize Weights Periodically

The 4060 pipeline instead ran DAgger as a PHASE 2: freeze a checkpoint, roll out,
save, retrain from scratch on the union. That is a different algorithm, and it
failed in a specific measurable way. Because expert convergence is geometric,
most steps of a converging trajectory sit near the goal (79.4% of round-0
rollouts had ||vel_si||<0.5), so aggregating whole rounds onto a far-heavy
uniform set drifted the training mix 1.8% -> 41% -> 56.3% near-goal, and the
closed-loop TE ratio got WORSE (1.350 -> 1.569) even while offline l_dir improved
64%: the model gained near-goal skill and lost the far field, which is where every
episode starts. Running both samplers concurrently is what keeps the database
balanced, and `frac` below makes that mix explicit rather than accidental.

This class owns the DAgger half of the database. It is a SEPARATE set of memmaps
from the uniform cache so the uniform half is never rewritten, pre-allocated to a
fixed reserve so rows can be filled in place while training reads them.

Layout (mirrors build_feature_cache so nothing new has to be learned):
    <dir>/fc.npy  float16 [R, H16,W16,C]  per PAIR
    <dir>/fd.npy  float16 [S, H16,W16,C]  per SCENE
    <dir>/ic.npy  uint8   [R, H,W,3]      per PAIR
    <dir>/id.npy  uint8   [S, H,W,3]      per SCENE
    <dir>/meta.pt vsi, tPo_norm, scene_id, pair_valid, scene_seq, seq, ingested

The reserve is a RING, not a high-water mark. The first concurrent run treated it
as the latter -- `ingest()` broke out on a `full()` check with no eviction -- and
so the pool sealed itself 800 iters in, at 8000 pairs from 249 scenes:

    iter 800:  [dagger] +1815 pairs -> 8000 pairs / 249 scenes
               [dagger] pool FULL (8000/8000 pairs, 249/1600 scenes); stopping ingest
    ...every ingest for the remaining 39200 iters was a no-op.

That silently demotes Fig. 3 back to the phase-2 algorithm it exists to replace:
the weight syncs, the policy reloads and the beta 1.0->0.3 schedule all keep
running, but nothing they produce ever reaches a batch, so 35% of every batch is
drawn from the same 249 scenes generated by a 800-iter-old policy. Both collectors
and both Isaac servers burn a GPU each for output that only accumulates on disk.

Eviction is FIFO over whole SCENES, oldest first. Two reasons it is by scene and
not by pair: pairs address their goal image indirectly, through `scene_id` into
fd/id, so recycling a scene slot under a live pair would silently repoint that
pair at a different scene's goal -- a corrupt label with no symptom but a worse
number. And DAgger wants the mix to track the current policy, so dropping the
oldest scene whole is the semantics we actually want. Reservoir sampling would be
the alternative (uniform over all history rather than the freshest R pairs), but
the far-field anchor is already the uniform half's job, per `frac` above.
"""
import glob
import os

import numpy as np
import torch

from cns.sim.supervisor import supervisor_vel, Policy


class DaggerPool:
    def __init__(self, cache_dir, H16, W16, C, H1=512, W1=512,
                 reserve_pairs=20000, reserve_scenes=4000, intrinsic=None,
                 min_tv=0.015, min_rw=0.012):
        """Reject a pair only when BOTH its translation and its rotation are below
        the resolvable floor. Thresholds are per-DOF, in the units each actually has.

        The previous gate was a single threshold on ||vel_si||, the mixed 6-vector.
        Rotation dominates that norm (measured median share 0.93), so the gate did
        NOT thin near-goal data uniformly -- it removed specifically the
        fine-TRANSLATION pairs. Measured over saved rollouts, of the pairs with
        TE < 20 mm it kept 19% and cut 81%, and the survivors had median RE 3.72 deg
        against the rejected pairs' 0.96 deg. In other words it kept "still needs
        rotating" and discarded "aligned but 8 mm off" -- which is exactly the skill
        needed to close from the measured 17-92 mm closed-loop stall to Table I's
        0.948 mm. The cut ended at ~16 mm and the stall band starts at 17 mm; those
        two numbers meeting was not a coincidence (Sec. 6.22).

        Defaults are half a 16px patch in each DOF. At the canonical intrinsics the
        image spans ~d* metres at distance d*, so one patch is d*/32, i.e. 1/32 in
        unit-world -> half a patch = 0.015. For rotation, a yaw of theta moves a
        mid-frame point by ~theta*1.25*f px, so one patch is ~0.025 rad -> half is
        0.012. Sec. 6.3's "drop what one 16px patch cannot resolve" is preserved
        per-DOF instead of being applied to a quantity with mixed units.

        NOTE this deliberately admits more near-goal data than before. Sec. 6.12's
        finding was that near-goal pile-up DOMINATING the mix hurt (1.8% -> 56%
        near-goal drove the closed loop worse), not that near-goal data is bad. The
        log-uniform subsampling in collect_dagger.py is what bounds the share; this
        gate only removes what is physically unresolvable.

        Belt-and-braces against the geometric pile-up described above. The
        collector already log-subsamples its states, but this pool is fed by
        whatever lands in a directory, so the unlearnable band is rejected here
        too. 0.05 is Sec. 6.3's recommendation: it keeps the useful near-goal band
        (~1.2-6 patches) and drops what one 16px patch cannot resolve.
        """
        from cns.utils.perception import CameraIntrinsic
        self.dir = cache_dir
        self.min_tv = float(min_tv)
        self.min_rw = float(min_rw)
        self.n_rejected = 0
        self.intr = intrinsic or CameraIntrinsic(W1, H1, 512, 512, W1 // 2, H1 // 2)
        os.makedirs(cache_dir, exist_ok=True)
        self.meta_p = os.path.join(cache_dir, "meta.pt")

        def mm(name, dtype, shape):
            p = os.path.join(cache_dir, name)
            mode = "r+" if os.path.exists(p) else "w+"
            if mode == "r+":
                return np.load(p, mmap_mode="r+")
            return np.lib.format.open_memmap(p, mode="w+", dtype=dtype, shape=shape)

        self.fc = mm("fc.npy", np.float16, (reserve_pairs, H16, W16, C))
        self.fd = mm("fd.npy", np.float16, (reserve_scenes, H16, W16, C))
        self.ic = mm("ic.npy", np.uint8, (reserve_pairs, H1, W1, 3))
        self.id = mm("id.npy", np.uint8, (reserve_scenes, H1, W1, 3))
        self.reserve_pairs = self.fc.shape[0]
        self.reserve_scenes = self.fd.shape[0]

        # One row per SLOT, not per live pair: with eviction the live rows are a
        # scattered subset of [0, reserve_pairs), so the metadata has to be
        # addressable by slot the way fc/ic already are.
        self.vsi = torch.zeros(self.reserve_pairs, 6)
        self.tpo = torch.zeros(self.reserve_pairs)
        self.scene_id = torch.zeros(self.reserve_pairs, dtype=torch.long)
        self.pair_valid = torch.zeros(self.reserve_pairs, dtype=torch.bool)
        self.scene_seq = torch.full((self.reserve_scenes,), -1, dtype=torch.long)
        self.seq = 0                # monotonic scene counter; defines FIFO order
        self.n_evicted = 0
        self.ingested = set()
        self._vr = None             # cached valid-row index, see _valid_rows()

        if os.path.exists(self.meta_p):
            m = torch.load(self.meta_p, map_location="cpu")
            self.ingested = set(m.get("ingested", []))
            if "pair_valid" in m:
                self.vsi = m["vsi"]; self.tpo = m["tPo_norm"]
                self.scene_id = m["scene_id"]; self.pair_valid = m["pair_valid"]
                self.scene_seq = m["scene_seq"]; self.seq = int(m["seq"])
                self.n_evicted = int(m.get("n_evicted", 0))
            else:
                # Pre-eviction meta: a contiguous prefix was live. Widen it into
                # the slot layout so an interrupted run can still be resumed.
                np_, ns_ = int(m["n_pairs"]), int(m["n_scenes"])
                self.vsi[:np_] = m["vsi"][:np_]
                self.tpo[:np_] = m["tPo_norm"][:np_]
                self.scene_id[:np_] = m["scene_id"][:np_]
                self.pair_valid[:np_] = True
                self.scene_seq[:ns_] = torch.arange(ns_)
                self.seq = ns_
        self.n_pairs = int(self.pair_valid.sum())
        self.n_scenes = int((self.scene_seq >= 0).sum())

    # ------------------------------------------------------------------
    def save_meta(self):
        torch.save({"vsi": self.vsi, "tPo_norm": self.tpo,
                    "scene_id": self.scene_id, "pair_valid": self.pair_valid,
                    "scene_seq": self.scene_seq, "seq": self.seq,
                    "n_evicted": self.n_evicted,
                    "ingested": sorted(self.ingested)}, self.meta_p)

    def _valid_rows(self):
        """Live pair slots. Cached because the trainer asks once per iter and the
        mask only changes on ingest/evict."""
        if self._vr is None:
            self._vr = self.pair_valid.nonzero(as_tuple=True)[0]
        return self._vr

    def sample(self, n):
        """n pair slots drawn with replacement from the live rows.

        Callers must go through this rather than randint(0, n_pairs): once
        eviction starts, live rows are no longer the prefix [0, n_pairs).
        """
        if n <= 0 or self.n_pairs == 0:
            return torch.zeros(0, dtype=torch.long)
        rows = self._valid_rows()
        return rows[torch.randint(0, len(rows), (n,))]

    def _evict_scene(self, protect=None):
        """Drop the oldest live scene and every pair addressing it.

        Returns the freed pair slots. `protect` is the scene being filled right
        now -- evicting it mid-ingest would leave its already-written pairs
        pointing at a slot that is about to be reused.
        """
        live = self.scene_seq >= 0
        if protect is not None:
            live = live.clone()
            live[protect] = False
        idx = live.nonzero(as_tuple=True)[0]
        if len(idx) == 0:
            return torch.zeros(0, dtype=torch.long)
        victim = int(idx[self.scene_seq[idx].argmin()])
        mask = self.pair_valid & (self.scene_id == victim)
        rows = mask.nonzero(as_tuple=True)[0]
        self.pair_valid[mask] = False
        self.scene_seq[victim] = -1
        self.n_pairs -= len(rows)
        self.n_scenes -= 1
        self.n_evicted += 1
        self._vr = None
        return rows

    def _alloc_scene(self):
        """A free scene slot, evicting the oldest scene if every slot is taken."""
        free = (self.scene_seq < 0).nonzero(as_tuple=True)[0]
        if len(free) == 0:
            self._evict_scene()
            free = (self.scene_seq < 0).nonzero(as_tuple=True)[0]
        si = int(free[0])
        # The invariant the whole scene-level design exists to hold: no live pair
        # may address a slot that is being handed out.
        assert not bool((self.pair_valid & (self.scene_id == si)).any()), \
            f"scene slot {si} still addressed by live pairs"
        self.scene_seq[si] = self.seq
        self.seq += 1
        self.n_scenes += 1
        return si

    @torch.no_grad()
    def ingest(self, scene_dir, backbone, device, policy=Policy.PBVS_Straight,
               max_scenes=64, batch=8, prune_ingested=False):
        """Encode any scene_*.npz not yet seen. Returns the number of new pairs.

        Cheap enough to call from inside the training loop: one scene is ~7 views,
        so ~7 backbone forwards (~0.1 s), against a collector that produces a scene
        every few seconds at worst.
        """
        files = sorted(glob.glob(os.path.join(scene_dir, "scene_*.npz")))
        new = [f for f in files if os.path.basename(f) not in self.ingested]
        if not new:
            return 0
        new = new[:max_scenes]

        dummy, dz = np.zeros((1, 2)), np.ones(1)
        added_pairs = 0
        for f in new:
            try:
                z = np.load(f)
                imgs, poses, wP = z["images"], z["poses"], z["wP"]
            except Exception as e:
                # A scene still being written by the collector will read as
                # truncated; skip it WITHOUT marking it ingested so the next pass
                # picks it up once complete.
                print(f"[dagger] skip {os.path.basename(f)} ({type(e).__name__})", flush=True)
                continue
            n_view = min(imgs.shape[0], poses.shape[0])
            if n_view < 2:
                self.ingested.add(os.path.basename(f))
                continue

            si = self._alloc_scene()
            des = torch.from_numpy(imgs[0]).permute(2, 0, 1)[None].to(device)
            self.fd[si] = backbone(des.float().div_(255.0)).to(
                torch.float16).cpu().numpy()[0]
            self.id[si] = imgs[0]

            free = [int(r) for r in (~self.pair_valid).nonzero(as_tuple=True)[0]]
            for k0 in range(1, n_view, batch):
                sl = slice(k0, min(k0 + batch, n_view))
                raw = imgs[sl]
                if len(raw) == 0:
                    break
                cur = torch.from_numpy(raw).permute(0, 3, 1, 2).to(device)
                fcur = backbone(cur.float().div_(255.0)).to(torch.float16).cpu().numpy()
                for j in range(len(raw)):
                    _, (tpo, vsi) = supervisor_vel(
                        policy, dummy, dz, dummy, dz, self.intr,
                        poses[sl.start + j], poses[0], wP)
                    tv = float(np.linalg.norm(vsi[:3]))
                    rw = float(np.linalg.norm(vsi[3:]))
                    if tv < self.min_tv and rw < self.min_rw:
                        self.n_rejected += 1
                        continue
                    if not free:
                        free = [int(r) for r in self._evict_scene(protect=si)]
                        if not free:
                            break       # reserve smaller than one scene
                    r = free.pop(0)
                    self.fc[r] = fcur[j]
                    self.ic[r] = raw[j]
                    self.vsi[r] = torch.from_numpy(np.asarray(vsi, dtype=np.float32))
                    self.tpo[r] = float(tpo)
                    self.scene_id[r] = si
                    self.pair_valid[r] = True
                    self.n_pairs += 1
                    added_pairs += 1
            self._vr = None
            self.ingested.add(os.path.basename(f))
            # The pool's memmaps now hold everything this scene contributes, so
            # the raw npz is redundant storage. The first 40k run kept both:
            # 19GB of pool + 16GB of already-ingested scenes in data/dagger_live,
            # on the same disk the run eventually filled.
            if prune_ingested:
                try:
                    os.remove(f)
                except OSError:
                    pass

        if added_pairs:
            self.fc.flush(); self.fd.flush(); self.ic.flush(); self.id.flush()
            self.save_meta()
        return added_pairs

    def stats(self):
        if self.n_pairs == 0:
            return "empty"
        v = self.vsi[self._valid_rows()]
        n = v.norm(dim=-1)
        tv = v[:, :3].norm(dim=-1)
        return (f"{self.n_pairs} pairs / {self.n_scenes} scenes, "
                f"||vel_si|| min {n.min():.3f} median {n.median():.3f}, "
                f"near-goal(<0.5) {100 * (n < 0.5).float().mean():.1f}%, "
                # Translation-only share of the near band is the number the old
                # combined gate hid; watch it rather than ||vel_si||.
                f"fine-trans(tv<0.05) {100 * (tv < 0.05).float().mean():.1f}%, "
                f"rejected(tv<{self.min_tv} AND rw<{self.min_rw}) {self.n_rejected}, "
                f"evicted {self.n_evicted} scenes")
